"""Modified the order to include a list of product IDs

Revision ID: 71ef62e8518f
Revises: 5de2f049bf67
Create Date: 2024-06-04 21:12:16.225823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ef62e8518f'
down_revision = '5de2f049bf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_ids', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'product_ids')
    # ### end Alembic commands ###
