"""Modified the order product and order schema

Revision ID: 75aa2f8d4880
Revises: a4e328ccadae
Create Date: 2024-06-05 20:53:08.548426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75aa2f8d4880'
down_revision = 'a4e328ccadae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_products_product_id_fkey', 'order_products', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_products_product_id_fkey', 'order_products', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
