"""Changed the image URL to image name in the images table

Revision ID: 7a6a375f5f28
Revises: 972afd268aac
Create Date: 2024-06-02 15:48:57.701870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6a375f5f28'
down_revision = '972afd268aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_name', sa.String(length=250), nullable=False))
    op.drop_column('images', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('images', 'image_name')
    # ### end Alembic commands ###
