"""Changed the image table

Revision ID: 934ca724a1bd
Revises: 30a2660e34df
Create Date: 2024-05-27 20:44:31.991363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934ca724a1bd'
down_revision = '30a2660e34df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_blob', sa.LargeBinary(), nullable=False))
    op.add_column('images', sa.Column('image_name', sa.String(), nullable=False))
    op.drop_column('images', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('images', 'image_name')
    op.drop_column('images', 'image_blob')
    # ### end Alembic commands ###
