"""Modified the order product and order schema

Revision ID: a4e328ccadae
Revises: b510023f1970
Create Date: 2024-06-05 20:45:04.314132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e328ccadae'
down_revision = 'b510023f1970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
