"""Modified the order product and order schema

Revision ID: b510023f1970
Revises: 71ef62e8518f
Create Date: 2024-06-05 20:33:50.139886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b510023f1970'
down_revision = '71ef62e8518f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'product_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_ids', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
