"""Modified the orders schema

Revision ID: fac76161c5df
Revises: 75aa2f8d4880
Create Date: 2024-06-06 21:09:22.850121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac76161c5df'
down_revision = '75aa2f8d4880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
